### ISSUE TITLE
Complete feature checklist

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/a11y-research#8]
Related to #7 as we might want to have an accessibility feature checklist as we prepare to deploy accessible john-travoltage.  @emily-phet started a draft checklist here:

https://docs.google.com/document/d/1jYx3wxNRxHHpMigxSFVvCRVFdB5-E-3_xbj9UI9uvWE/edit

From https://github.com/phetsims/scenery/issues/299, @samreid found another checklist from http://w3c.github.io/aria-in-html/#custom-control-accessible-development-checklist:

 - [ ] *focusable* Can you get to the control via the keyboard? Refer to Providing Keyboard Focus
 - [ ] *operable* Can you use the control with the keyboard? Refer to Keyboard Navigation
 - [ ] *expected* operation Can you use the standard keys for the control type to operate it. Refer to ARIA Widget Design Patterns
 - [ ] *clear* indication of focus Can you easily see it when the control has focus? Refer to Visible Focus (WCAG2)
 - [ ] *label* The control has a text label that is exposed as an accessible name in accessibility APIs
 - [ ] *role* The control has an appropriate role exposed in accessibility APIs
 states and properties The control has any UI states and properties that it has exposed in accessibility APIs
 - [ ] *color* contrast The control label/description/icon is perceivable/usable for low vision users (Use a color contrast checker.)
 - [ ] *high* contrast mode The control is perceivable/usable when High Contrast Mode is enabled (e.g. Windows HC mode)
